# Generated by Django 2.0 on 2018-04-09 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projektas',
            fields=[
                ('Project_name', models.CharField(max_length=100)),
                ('Project_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Color', models.IntegerField(blank=True, null=True)),
                ('Indent', models.IntegerField(blank=True, null=True)),
                ('Parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projektai.Projektas')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_Content', models.TextField(blank=True, null=True)),
                ('task_id', models.IntegerField(primary_key=True, serialize=False)),
                ('task_priority', models.IntegerField(blank=True, null=True)),
                ('task_indent', models.IntegerField(blank=True, null=True)),
                ('task_date_added', models.DateTimeField(blank=True, null=True)),
                ('task_due_date_utc', models.DateTimeField(blank=True, null=True)),
                ('task_parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projektai.Task')),
                ('task_project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektai.Projektas')),
                ('task_responsible_uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Collaborator')),
                ('task_uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_id', to='accounts.UserProfile')),
            ],
        ),
    ]
