# Generated by Django 2.0 on 2018-04-13 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Old_Projektas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_name', models.CharField(max_length=100)),
                ('Project_ID', models.IntegerField(blank=True, null=True)),
                ('Color', models.IntegerField(blank=True, null=True)),
                ('Indent', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.IntegerField(blank=True, null=True)),
                ('is_archived', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Old_Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_Content', models.TextField(blank=True, null=True)),
                ('task_id', models.IntegerField()),
                ('task_priority', models.IntegerField(blank=True, null=True)),
                ('task_indent', models.IntegerField(blank=True, null=True)),
                ('task_date_added', models.DateTimeField(blank=True, null=True)),
                ('task_due_date_utc', models.DateTimeField(blank=True, null=True)),
                ('checked', models.IntegerField(blank=True, null=True)),
                ('in_history', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projektas',
            fields=[
                ('Project_name', models.CharField(max_length=100)),
                ('Project_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Color', models.IntegerField(blank=True, null=True)),
                ('Indent', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.IntegerField(blank=True, null=True)),
                ('is_archived', models.IntegerField(blank=True, null=True)),
                ('Parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projektai.Projektas')),
                ('Project_token', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.UserProfile', to_field='token')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_Content', models.TextField(blank=True, null=True)),
                ('task_id', models.IntegerField(primary_key=True, serialize=False)),
                ('task_priority', models.IntegerField(blank=True, null=True)),
                ('task_indent', models.IntegerField(blank=True, null=True)),
                ('task_date_added', models.DateTimeField(blank=True, null=True)),
                ('task_due_date_utc', models.DateTimeField(blank=True, null=True)),
                ('checked', models.IntegerField(blank=True, null=True)),
                ('in_history', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.IntegerField(blank=True, null=True)),
                ('task_parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projektai.Task')),
                ('task_project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektai.Projektas')),
                ('task_responsible_uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Collaborator')),
                ('task_uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_id', to='accounts.Collaborator')),
            ],
        ),
        migrations.AddField(
            model_name='old_task',
            name='task_parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projektai.Task'),
        ),
        migrations.AddField(
            model_name='old_task',
            name='task_project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektai.Projektas'),
        ),
        migrations.AddField(
            model_name='old_task',
            name='task_responsible_uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Collaborator'),
        ),
        migrations.AddField(
            model_name='old_task',
            name='task_uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_task_id', to='accounts.Collaborator'),
        ),
        migrations.AddField(
            model_name='old_projektas',
            name='Parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projektai.Projektas'),
        ),
        migrations.AddField(
            model_name='old_projektas',
            name='Project_token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.UserProfile', to_field='token'),
        ),
    ]
