# Generated by Django 2.0 on 2018-04-11 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180410_0023'),
        ('projektai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projektas',
            name='Project_token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.UserProfile', to_field='token'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_id', to='accounts.Collaborator'),
        ),
    ]
