# Generated by Django 2.0 on 2018-04-18 23:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektai', '0004_auto_20180419_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='old_projektas',
            name='when_deleted',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 19, 2, 27, 24, 192924)),
        ),
        migrations.AlterField(
            model_name='old_task',
            name='when_deleted',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 19, 2, 27, 24, 193930)),
        ),
        migrations.AlterField(
            model_name='projektas',
            name='Project_ID',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
