# Generated by Django 2.0 on 2018-04-20 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektai', '0007_auto_20180420_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='old_projektas',
            name='when_deleted',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 20, 13, 48, 37, 3682)),
        ),
        migrations.AlterField(
            model_name='old_task',
            name='task_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='old_task',
            name='when_deleted',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 20, 13, 48, 37, 4184)),
        ),
        migrations.AlterField(
            model_name='syncedstuff',
            name='sync_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 20, 13, 48, 37, 1680)),
        ),
    ]
