# Generated by Django 2.0 on 2018-04-09 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('full_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(blank=True, null=True, unique=True)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('inbox_project', models.IntegerField(blank=True, null=True)),
                ('start_day', models.IntegerField(blank=True, null=True)),
                ('next_week', models.IntegerField(blank=True, null=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_host', models.CharField(blank=True, max_length=50, null=True)),
                ('completed_count', models.IntegerField(blank=True, null=True)),
                ('completed_today', models.IntegerField(blank=True, null=True)),
                ('karma', models.IntegerField(blank=True, null=True)),
                ('karma_trend', models.CharField(blank=True, max_length=20, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('premium_until', models.CharField(blank=True, max_length=100, null=True)),
                ('is_biz_admin', models.BooleanField(default=False)),
                ('join_date', models.DateTimeField(blank=True, null=True)),
                ('business_account_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.UserProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
