# Generated by Django 2.0 on 2018-05-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180508_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='old_versions_count',
            field=models.IntegerField(default=5),
        ),
    ]
