# Generated by Django 2.0 on 2018-05-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_old_versions_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='old_versions_count',
            field=models.IntegerField(default=10),
        ),
    ]
