# Generated by Django 2.0 on 2018-04-20 10:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180419_0227'),
        ('projektai', '0005_auto_20180419_0227'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncedStuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_time', models.DateTimeField(default=datetime.datetime(2018, 4, 20, 13, 41, 11, 638993))),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile', to_field='token')),
            ],
        ),
        migrations.AlterField(
            model_name='old_projektas',
            name='Project_ID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='old_projektas',
            name='when_deleted',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 20, 13, 41, 11, 640494)),
        ),
        migrations.AlterField(
            model_name='old_task',
            name='when_deleted',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 20, 13, 41, 11, 641976)),
        ),
    ]
