# Generated by Django 2.0 on 2018-04-21 09:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektai', '0009_auto_20180420_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='old_projektas',
            name='when_deleted',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 21, 12, 42, 54, 28886)),
        ),
        migrations.AlterField(
            model_name='old_task',
            name='task_responsible_uid',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='old_task',
            name='task_uid',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='old_task',
            name='when_deleted',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 21, 12, 42, 54, 28886)),
        ),
        migrations.AlterField(
            model_name='projektas',
            name='Project_token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile', to_field='token'),
        ),
        migrations.AlterField(
            model_name='syncedstuff',
            name='sync_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 21, 12, 42, 54, 26857)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projektai.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektai.Projektas'),
        ),
    ]
