# Generated by Django 2.0 on 2018-04-22 06:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180419_0227'),
        ('projektai', '0012_auto_20180422_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='old_task',
            name='Project_token',
        ),
        migrations.AddField(
            model_name='old_task',
            name='Task_token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile', to_field='token'),
        ),
        migrations.AlterField(
            model_name='old_projektas',
            name='when_deleted',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 22, 9, 11, 17, 530219)),
        ),
        migrations.AlterField(
            model_name='old_task',
            name='when_deleted',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 22, 9, 11, 17, 531222)),
        ),
        migrations.AlterField(
            model_name='syncedstuff',
            name='sync_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 22, 9, 11, 17, 528213)),
        ),
    ]
