# Generated by Django 2.0 on 2018-04-24 22:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180419_0227'),
        ('projektai', '0016_auto_20180422_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile', to_field='token'),
        ),
        migrations.AlterField(
            model_name='old_projektas',
            name='when_deleted',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 24, 19, 2, 16, 429479, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='old_task',
            name='when_deleted',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 24, 19, 2, 16, 429983, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='syncedstuff',
            name='sync_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 24, 19, 2, 16, 427473, tzinfo=utc)),
        ),
    ]
