# Generated by Django 2.0 on 2018-04-27 13:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projektai', '0028_auto_20180426_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='old_projektas',
            name='item_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='old_projektas',
            name='when_deleted',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 27, 10, 58, 52, 389441, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='old_task',
            name='when_deleted',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 27, 10, 58, 52, 389943, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='syncedstuff',
            name='sync_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 27, 10, 58, 52, 386936, tzinfo=utc)),
        ),
    ]
