# Generated by Django 2.0 on 2018-04-29 15:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projektai', '0030_auto_20180429_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_parent_id',
        ),
        migrations.AddField(
            model_name='task',
            name='item_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='old_projektas',
            name='when_deleted',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 29, 12, 52, 24, 46762, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='old_task',
            name='when_deleted',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 29, 12, 52, 24, 47263, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='syncedstuff',
            name='sync_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 29, 12, 52, 24, 44256, tzinfo=utc)),
        ),
    ]
