# Generated by Django 2.0 on 2018-04-29 15:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projektai', '0031_auto_20180429_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='old_task',
            name='task_parent_id',
        ),
        migrations.AddField(
            model_name='old_task',
            name='item_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='old_projektas',
            name='when_deleted',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 29, 12, 53, 3, 366275, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='old_task',
            name='when_deleted',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 29, 12, 53, 3, 367277, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='syncedstuff',
            name='sync_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 29, 12, 53, 3, 364771, tzinfo=utc)),
        ),
    ]
