# Generated by Django 2.0 on 2018-05-08 14:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projektai', '0032_auto_20180429_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='old_projektas',
            name='when_deleted',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 8, 11, 4, 44, 340849, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='old_task',
            name='when_deleted',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 8, 11, 4, 44, 341372, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projektas',
            name='Project_token',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile', to_field='token'),
        ),
        migrations.AlterField(
            model_name='syncedstuff',
            name='sync_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 8, 11, 4, 44, 338342, tzinfo=utc)),
        ),
    ]
